linters:
  enable-all: true
  disable:
    - goconst
    - gosec
    - errcheck
    - gocritic
    - structcheck

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 12
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 190
