language: go
go:
  - "1.11"

go_import_path: github.com/fmitra/srp

env:
  - GO111MODULE=on

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.12

jobs:
  include:
    - stage: test
      script:
        - make test_and_lint
      after_success:
        - bash <(curl -s https://codecov.io/bash)
