sudo: required

language: go
go:
  - "1.11"

go_import_path: github.com/fmitra/srp

jobs:
  include:
    - stage: test
      script:
        - make ci_dependencies
        - make test_and_lint
      after_success:
        - bash <(curl -s https://codecov.io/bash)
